2023-06-23 17:46:44,333 ERROR 'Car' object has no attribute 'model_no'
Traceback (most recent call last):
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\game.py", line 9, in <module>
    game_loop.looping()
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\game_loop.py", line 121, in looping
    self._02_level.update(dt)
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\_02_main.py", line 338, in update
    self.update_cars_timers()
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\_02_main.py", line 301, in update_cars_timers
    cars_timer.update()
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\car.py", line 228, in update
    self.spawn_car()
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\car.py", line 212, in spawn_car
    Car(groups=self.groups,
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\car.py", line 25, in __init__
    super().__init__(groups=groups,
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\entity.py", line 19, in __init__
    self.set_hitbox(pos)
  File "C:\Users\kevin\PycharmProjects\Super_Mario_Bros_The_Movie_The_Game\code\_02_level\car.py", line 56, in set_hitbox
    if self.model_no == 1:
       ^^^^^^^^^^^^^
AttributeError: 'Car' object has no attribute 'model_no'
